// Package relay owns the service relay sidecar (§8): resolving the configured
// services into fixed listener ports, rendering the haproxy configuration and
// the generated client wiring (~/.ssh/config, services.json), and the
// git-remote conflict check that keeps the relay from quietly reopening the
// git write path §4 closed.
//
// The relay is a byte pipe, one listener per service. The listener port *is*
// the destination — there is no field the agent can put a different host into
// — so this is structural enforcement, not policy over a client-supplied
// target. See docs/PLAN.md §8.
package relay

import (
	"encoding/json"
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/scuq/aibox/internal/config"
)

const (
	// Name is the relay sidecar's fixed container name and the HostName the
	// generated ssh config points at.
	Name = "aibox-relay"
	// BasePort is where auto-allocated listener ports start.
	BasePort = 2200
	// ConfigContainerPath is where the rendered haproxy.cfg is mounted.
	ConfigContainerPath = "/etc/haproxy/haproxy.cfg"
)

// RelayIP derives the sidecar's fixed address: host .3 of the internal subnet
// (squid is .2, the gateway .1). Derived arithmetically, never resolved by
// container name — name resolution on internal networks varies across podman
// versions (§8.12).
func RelayIP(subnet string) (string, error) {
	ip, _, err := net.ParseCIDR(subnet)
	if err != nil {
		return "", fmt.Errorf("invalid egress subnet %q: %w", subnet, err)
	}
	v4 := ip.To4()
	if v4 == nil {
		return "", fmt.Errorf("egress subnet %q is not IPv4", subnet)
	}
	v4[3] = 3
	return v4.String(), nil
}

// Service is a configured service with its resolved listener port.
type Service struct {
	config.ServiceConfig
	Port int
}

// Proto returns the effective protocol ("tcp" default).
func (s Service) Proto() string {
	if s.ServiceConfig.Proto == "" {
		return "tcp"
	}
	return s.ServiceConfig.Proto
}

// BackendHost returns the host part of the backend "host:port".
func (s Service) BackendHost() string {
	if h, _, err := net.SplitHostPort(s.Backend); err == nil {
		return h
	}
	return s.Backend
}

// Resolve assigns a listener port to every service: explicit `listen:` wins,
// the rest are allocated in declaration order from BasePort, skipping any port
// an explicit entry already claimed. A collision between two explicit ports is
// an error — silently sharing a listener would make one service unreachable.
func Resolve(services []config.ServiceConfig) ([]Service, error) {
	claimed := map[int]string{}
	for _, s := range services {
		if s.Listen != 0 {
			if other, ok := claimed[s.Listen]; ok {
				return nil, fmt.Errorf("services %q and %q both request listener port %d", other, s.Name, s.Listen)
			}
			claimed[s.Listen] = s.Name
		}
	}
	out := make([]Service, 0, len(services))
	next := BasePort
	for _, s := range services {
		port := s.Listen
		if port == 0 {
			for claimed[next] != "" {
				next++
			}
			port = next
			claimed[port] = s.Name
			next++
		}
		out = append(out, Service{ServiceConfig: s, Port: port})
	}
	return out, nil
}

// HAProxyConfig renders the sidecar configuration: one `listen` section per
// TCP service. UDP services are handled by a socat companion (see the
// Containerfile / entrypoint), not haproxy, and are skipped here.
func HAProxyConfig(services []Service) string {
	var b strings.Builder
	b.WriteString("# Generated by aibox — do not edit; edit the services list and run\n")
	b.WriteString("# 'aibox relay restart'.\n")
	b.WriteString("global\n")
	b.WriteString("    log stdout format raw local0\n")
	b.WriteString("    maxconn 256\n")
	b.WriteString("defaults\n")
	b.WriteString("    mode tcp\n")
	b.WriteString("    log global\n")
	b.WriteString("    option tcplog\n")
	b.WriteString("    timeout connect 5s\n")
	b.WriteString("    timeout client 1h\n")
	b.WriteString("    timeout server 1h\n")
	for _, s := range services {
		if s.Proto() != "tcp" {
			continue
		}
		fmt.Fprintf(&b, "\nlisten svc_%s\n", sanitize(s.Name))
		fmt.Fprintf(&b, "    bind 0.0.0.0:%d\n", s.Port)
		if s.IdleTimeout != "" {
			fmt.Fprintf(&b, "    timeout client %s\n", s.IdleTimeout)
			fmt.Fprintf(&b, "    timeout server %s\n", s.IdleTimeout)
		}
		maxconn := s.MaxConns
		if maxconn <= 0 {
			maxconn = 4
		}
		fmt.Fprintf(&b, "    maxconn %d\n", maxconn)
		fmt.Fprintf(&b, "    server backend %s check\n", s.Backend)
	}
	return b.String()
}

// sanitize makes a service name safe as an haproxy section suffix.
func sanitize(name string) string {
	var b strings.Builder
	for _, r := range name {
		if r == '-' || r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// SSHConfig renders ~/.ssh/config so the agent addresses services by name, not
// port. HostKeyAlias keys known_hosts to device identity rather than
// [relay]:port, so host keys survive port churn and two services on the same
// relay stay distinguishable (§8.4) — this is the detail most likely to be
// omitted and most annoying to debug.
//
// relayHost is the relay's derived IP (not the name), consistent with §8.12's
// "never resolve by container name".
func SSHConfig(services []Service, relayHost string) string {
	var b strings.Builder
	b.WriteString("# Generated by aibox — the relay's named services (§8.3). Read-only.\n")
	for _, s := range services {
		if s.Proto() != "tcp" {
			continue
		}
		hosts := append([]string{s.Name}, s.Aliases...)
		fmt.Fprintf(&b, "\nHost %s\n", strings.Join(hosts, " "))
		fmt.Fprintf(&b, "    HostName        %s\n", relayHost)
		fmt.Fprintf(&b, "    Port            %d\n", s.Port)
		fmt.Fprintf(&b, "    HostKeyAlias    %s\n", s.Name)
		b.WriteString("    User            %r\n")
	}
	return b.String()
}

// ServiceInfo is one entry of the machine-readable inventory.
type ServiceInfo struct {
	Name             string   `json:"name"`
	Proto            string   `json:"proto"`
	Address          string   `json:"address"`
	Aliases          []string `json:"aliases,omitempty"`
	BackendDisclosed bool     `json:"backend_disclosed"`
	Backend          string   `json:"backend,omitempty"`
}

// Inventory builds the services.json payload. The real backend appears only
// when the service opted in with BackendDisclosed — default false, so the
// agent gets a name and a way to reach it, not a map of the network.
func Inventory(services []Service, relayHost string) []ServiceInfo {
	out := make([]ServiceInfo, 0, len(services))
	for _, s := range services {
		proto := "ssh"
		if s.Proto() == "udp" {
			proto = "udp"
		} else if p := backendPort(s.Backend); p != "22" {
			proto = "tcp"
		}
		info := ServiceInfo{
			Name:             s.Name,
			Proto:            proto,
			Address:          fmt.Sprintf("%s:%d", relayHost, s.Port),
			Aliases:          s.Aliases,
			BackendDisclosed: s.BackendDisclosed,
		}
		if s.BackendDisclosed {
			info.Backend = s.Backend
		}
		out = append(out, info)
	}
	return out
}

// InventoryJSON renders the inventory as newline-delimited JSON objects, the
// shape the plan's services.json sketch uses.
func InventoryJSON(services []Service, relayHost string) ([]byte, error) {
	var b strings.Builder
	for _, info := range Inventory(services, relayHost) {
		line, err := json.Marshal(info)
		if err != nil {
			return nil, err
		}
		b.Write(line)
		b.WriteByte('\n')
	}
	return []byte(b.String()), nil
}

func backendPort(backend string) string {
	if _, p, err := net.SplitHostPort(backend); err == nil {
		return p
	}
	return ""
}

// GitRemoteConflict is a service whose backend host matches a git remote.
type GitRemoteConflict struct {
	Service string
	Backend string
	Remote  string
	URL     string
}

// FindGitRemoteConflicts compares service backends against the workspace's git
// remotes (§8.9). A match means SSH to that host becomes possible at the
// network layer, so `git push` over it would work and the read-only .git mount
// (§4 layer 1) is the only thing left standing. Warned loudly, never a refusal
// — there are legitimate reasons to reach a host that also serves git.
//
// remotes maps remote name → URL, as `git remote -v` reports.
func FindGitRemoteConflicts(services []Service, remotes map[string]string) []GitRemoteConflict {
	var out []GitRemoteConflict
	for _, s := range services {
		host := strings.ToLower(s.BackendHost())
		if host == "" {
			continue
		}
		for name, url := range remotes {
			if strings.Contains(strings.ToLower(url), host) {
				out = append(out, GitRemoteConflict{
					Service: s.Name, Backend: s.Backend, Remote: name, URL: url,
				})
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Service < out[j].Service })
	return out
}
