// Package devcontainer generates and manages VS Code Dev Containers wired to
// the aibox image, volumes and hardening.
//
// Why this exists at all (ported from bclaude): the Claude Code extension
// talks to the CLI over a loopback WebSocket on a random port, advertised in
// $CLAUDE_CONFIG_DIR/ide/<port>.lock — precisely the thing a separate network
// namespace can't reach. The clean fix is to move the VS Code server *into*
// the container: server, extension and CLI share a loopback, diffs and
// selection context work, and the egress posture is untouched.
package devcontainer

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/scuq/aibox/internal/assistant"
	"github.com/scuq/aibox/internal/config"
	"github.com/scuq/aibox/internal/container"
	"github.com/scuq/aibox/internal/egress"
	"github.com/scuq/aibox/internal/git"
	"github.com/scuq/aibox/internal/image"
	"github.com/scuq/aibox/internal/notes"
	"github.com/scuq/aibox/internal/project"
)

// Options is everything Generate needs, resolved by the caller.
type Options struct {
	Config      config.Config
	Workspace   string // canonical
	ProjectID   string
	ProjectName string
	Assistants  []assistant.Assistant
	GitMounts   git.Mounts
	// Fresh adds an image rebuild to the initializeCommand and --rm so the
	// container is recreated from the fresh image rather than revived.
	Fresh   bool
	SELinux bool

	// EphemeralHostPath / EphemeralMount wire the host-shared scratch dir into
	// the devcontainer. Empty when disabled.
	EphemeralHostPath string
	EphemeralMount    string
}

// Name is the devcontainer's display name.
func (o Options) Name() string {
	if o.Config.Devcontainer.Name != "" {
		return o.Config.Devcontainer.Name
	}
	return o.ProjectName + "-aibox"
}

// mountString renders one devcontainer "mounts" entry (docker --mount
// syntax). This is presentation of an already-rendered decision, not a second
// mount renderer: sources and read-only-ness come from container.Mount values
// produced by the same code paths as `aibox run`.
func mountString(m container.Mount, selinux bool) string {
	s := fmt.Sprintf("source=%s,target=%s,type=%s", m.Source, m.Dest, m.Type)
	for _, o := range m.Options {
		if o == "ro" {
			s += ",readonly"
		} else {
			s += "," + o
		}
	}
	if selinux && m.Type == container.MountBind {
		s += ",z"
	}
	return s
}

// Generate renders devcontainer.json. JSONC on purpose — the comments carry
// the reasons, and Dev Containers reads comments fine.
func Generate(o Options) (string, error) {
	// A devcontainer is ALWAYS network-isolated: it joins only aibox-internal
	// (no route out) with the squid proxy env set, regardless of egress.mode.
	// A persistent IDE-attached container must never silently sit on podman's
	// default route-out network. Forcing proxy mode here makes the network and
	// proxy-env blocks below fire unconditionally, and the policy layer in the
	// notes reflect it. `open` mode only ever governs ephemeral `aibox run`.
	o.Config.Egress.Mode = "proxy"
	cfg := o.Config
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	relabel := ""
	if o.SELinux {
		relabel = ",z"
	}

	w(`// Generated by 'aibox devcontainer create' — VS Code attached to the aibox
// image with the same volumes, hardening and git policy as 'aibox run'.
//
// Needs the Dev Containers extension, with podman as the runtime:
//   "dev.containers.dockerPath": "podman"
// The image must exist first: run 'aibox image build'.
{
    "name": %q,
    "image": %q,
    "workspaceFolder": "/work",
    "workspaceMount": "source=${localWorkspaceFolder},target=/work,type=bind%s",
`, o.Name(), image.Ref(cfg), relabel)

	// The Dev Container five. All five, together, always: without them Dev
	// Containers derives its own localhost/vsc-<project>-<hash>-uid image
	// purely to rewrite the container user's uid — redundant against the
	// keep-id mapping below, fighting it (the volumes are owned by 1000), and
	// a second cached image between you and 'aibox image build'.
	w(`    "overrideCommand": true,
    "containerUser": "aibox",
    "remoteUser": "aibox",
    "updateRemoteUserUID": false,
`)

	// initializeCommand runs on the host before every start. It brings the
	// isolated network + squid up ('aibox net up') so the forced
	// --network=aibox-internal below can never fail with "network not found",
	// and (with --fresh) rebuilds the image first. Needs aibox on the host
	// PATH, which `make install` provides.
	initCmd := "aibox net up"
	if o.Fresh {
		// --fresh: rebuild before every start so an aibox/image you updated
		// reaches this project without remembering to rebuild, then net up.
		initCmd = fmt.Sprintf("aibox image build --image %s && aibox net up", shellQuote(image.Ref(cfg)))
	}
	initJSON, _ := json.Marshal([]string{"/bin/sh", "-c", initCmd})
	w("    \"initializeCommand\": %s,\n", initJSON)

	// Volumes: per-assistant config+auth, the shared cache, and the read-only
	// .git policy mounts — the same decisions `aibox run` makes.
	var mounts []container.Mount
	for _, a := range o.Assistants {
		mounts = append(mounts, a.ConfigMounts(o.ProjectID)...)
	}
	mounts = append(mounts, container.Mount{
		Type: container.MountVolume, Source: project.CacheVolumeName, Dest: "/home/aibox/.cache",
	})
	if o.EphemeralHostPath != "" {
		mounts = append(mounts, container.Mount{
			Type: container.MountBind, Source: o.EphemeralHostPath, Dest: o.EphemeralMount,
		})
	}
	mounts = append(mounts, o.GitMounts.Mounts...)
	w("    \"mounts\": [\n")
	for i, m := range mounts {
		comma := ","
		if i == len(mounts)-1 {
			comma = ""
		}
		w("        %q%s\n", mountString(m, o.SELinux), comma)
	}
	w("    ],\n")

	// Same flags as 'aibox run' (memory/cpu caps are left out: they would
	// fail on hosts without delegated cgroups, and this file may travel).
	w("    \"runArgs\": [\n")
	if o.Fresh || cfg.Devcontainer.RemoveOnStop {
		w(`        // The container is thrown away when VS Code stops it, so the next
        // start creates one from the current image instead of reviving a
        // snapshot of an older one. What that costs you is anything installed
        // into the container layer; caches, config and the VS Code server all
        // live in volumes and survive.
        "--rm",
`)
	}
	w("        \"--userns=keep-id:uid=1000,gid=1000\",\n")
	w("        \"--security-opt=no-new-privileges\",\n")
	w("        \"--cap-drop=ALL\",\n")
	w("        \"--pids-limit=%d\",\n", cfg.Security.PidsLimit)
	// The labels are what let 'aibox devcontainer stop|remove|status' own this
	// container's lifecycle even though VS Code created it. Cleanup queries
	// these, never names.
	labels := container.BaseLabels(container.RoleWorkspace)
	labels[container.LabelMode] = container.ModeDevcontainer
	labels[container.LabelProjectID] = o.ProjectID
	labels[container.LabelProjectPath] = o.Workspace
	labels[container.LabelAssistant] = assistantNames(o.Assistants)
	for _, kv := range sortedLabelArgs(labels) {
		w("        %q,\n", "--label="+kv)
	}
	// Always the internal network: no route out except the squid sidecar. The
	// initializeCommand above (aibox net up) guarantees it exists and squid is
	// running before this container starts; the VS Code server download hosts
	// are in the base allowlist.
	w("        \"--network=%s\",\n", egress.NetInternal)
	for _, t := range o.GitMounts.Tmpfs {
		w("        %q,\n", strings.Join(t.Args(), "="))
	}
	// mode=1777 (not uid=/gid=, which podman's --tmpfs rejects) so uid 1000
	// can write the notes under cap-drop=ALL.
	w("        \"--tmpfs=/run/aibox:rw,nosuid,nodev,mode=1777,size=64k\",\n")
	w("        \"--tmpfs=/tmp:rw,nosuid,nodev,exec,size=%s\"\n", cfg.Runtime.TmpfsSize)
	w("    ],\n")

	{
		// Always set: the container's only route out is squid, so tools must
		// be told where the one door is (both cases — curl reads one, most
		// CLIs the other).
		proxyURL, err := egress.ProxyURL(cfg.Egress.Subnet)
		if err != nil {
			return "", err
		}
		w(`    "containerEnv": {
        "HTTPS_PROXY": %[1]q,
        "https_proxy": %[1]q,
        "HTTP_PROXY": %[1]q,
        "http_proxy": %[1]q,
        "NO_PROXY": %[2]q,
        "no_proxy": %[2]q
    },
`, proxyURL, egress.NoProxy)
	}

	// Dev Containers starts the container with its own --entrypoint, so
	// aibox's entrypoint.sh — which renders /run/aibox/ainotes.md and copies
	// the login from the shared auth volume into the per-project config volume
	// — never runs here. postStartCommand does the same two things on every
	// container start, so a devcontainer is logged in and the agent has its
	// environment notes without a prior `aibox run`.
	if cmd := postStartCommand(o); cmd != "" {
		encoded, _ := json.Marshal(cmd)
		w("    \"postStartCommand\": %s,\n", encoded)
	}

	// Extensions: the assistants' own, the toolchain ones, then whatever the
	// project config adds. The Go and Python toolchains are in the image, so
	// the extensions are pointed at them rather than left to install their
	// own — the Go extension's tool bootstrap in particular wants a module
	// proxy that egress proxy mode may not be allowing.
	exts := []string{}
	for _, a := range o.Assistants {
		switch a.Name() {
		case "claude":
			exts = append(exts, "anthropic.claude-code")
		case "codex":
			exts = append(exts, "openai.chatgpt")
		}
	}
	exts = append(exts, "golang.go", "ms-python.python", "ms-python.debugpy", "charliermarsh.ruff")
	exts = append(exts, cfg.Devcontainer.VSCode.Extensions...)
	exts = dedupe(exts)

	w("    \"customizations\": {\n        \"vscode\": {\n            \"extensions\": [\n")
	for i, e := range exts {
		comma := ","
		if i == len(exts)-1 {
			comma = ""
		}
		w("                %q%s\n", e, comma)
	}
	w(`            ],
            "settings": {
                "go.goroot": "/usr/local/go",
                "go.gopath": "/home/aibox/.cache/go",
                "go.toolsGopath": "/usr/local/go-tools",
                "go.toolsManagement.checkForUpdates": "off",
                "go.toolsManagement.autoUpdate": false,
                "go.alternateTools": {
                    "gopls": "/usr/local/go-tools/bin/gopls",
                    "dlv": "/usr/local/go-tools/bin/dlv",
                    "staticcheck": "/usr/local/go-tools/bin/staticcheck"
                },
                "python.defaultInterpreterPath": "/usr/bin/python3",
                "ruff.path": ["/usr/local/bin/ruff"],
                "terminal.integrated.defaultProfile.linux": "bash"
            }
        }
    }
}
`)
	return b.String(), nil
}

// postStartCommand assembles the shell run on every devcontainer start: seed
// each assistant's login from its shared auth volume (only when the config
// volume has none, so a refreshed token is never clobbered), then render the
// environment notes into /run/aibox/ainotes.md and link ~/.ainotes. The
// policy layer is embedded base64-encoded so its newlines and punctuation
// survive the trip through JSON and the shell without quoting hazards.
func postStartCommand(o Options) string {
	var parts []string
	for _, a := range o.Assistants {
		auth := a.Auth()
		if auth == nil {
			continue
		}
		src := auth.AuthDir + "/" + auth.CredentialFile
		dst := auth.ConfigDir + "/" + auth.CredentialFile
		parts = append(parts, fmt.Sprintf(
			"if [ -s %s ] && [ ! -s %s ]; then install -m 600 %s %s 2>/dev/null || true; fi",
			src, dst, src, dst))
	}
	policy := notes.PolicyLayer(o.Config)
	b64 := base64.StdEncoding.EncodeToString([]byte(policy))
	parts = append(parts,
		"cat /usr/share/aibox/ainotes-image.md 2>/dev/null > /run/aibox/ainotes.md || true",
		fmt.Sprintf("printf %%s %s | base64 -d >> /run/aibox/ainotes.md 2>/dev/null || true", b64),
		`ln -sf /run/aibox/ainotes.md "$HOME/.ainotes" 2>/dev/null || true`,
	)
	return strings.Join(parts, "; ")
}

// shellQuote single-quotes a token for embedding in a /bin/sh command.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func assistantNames(as []assistant.Assistant) string {
	names := make([]string, 0, len(as))
	for _, a := range as {
		names = append(names, a.Name())
	}
	if len(names) == 0 {
		return "none"
	}
	return strings.Join(names, ",")
}

func sortedLabelArgs(labels map[string]string) []string {
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	// Deterministic output keeps the golden tests honest.
	sort.Strings(keys)
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, k+"="+labels[k])
	}
	return out
}

func dedupe(in []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
